/**
 * Created by Administrator on 2016/1/15.
 */

$(function() {
    $('.banner').unslider(
        {
            speed:900,
            delay:3000,
            complete: function() {},  //  动画完成的回调函数
            keys: true,               //  启动键盘导航
            dots: true,               //  显示点导航
            fluid: true,              //  支持响应式设计
            // animation: 'fade',
            autoplay: true
            // arrows: false
        }
    );
    $(".s2").hover(
        function(){
            $(".s2_a2").show("slow")
        },
        function(){
            $(".s2_a2").hide("slow")
        }
    );
    $(".s4").hover(
        function(){
            $(".s4_a4").show("slow")
        },
        function(){
            $(".s4_a4").hide("slow")
        }
    );
    $(".s6").hover(
        function(){
            $(".s6_a6").show("slow")
        },
        function(){
            $(".s6_a6").hide("slow")
        }
    );
    $(".s9").hover(
        function(){
            $(".s9_a9").show("slow")
        },
        function(){
            $(".s9_a9").hide("slow")
        }
    );
    $(".t2").hover(
        function(){
            $(".t2_a2").show("slow")
        },
        function(){
            $(".t2_a2").hide("slow")
        }
    );
    $(".t4").hover(
        function(){
            $(".t4_a4").show("slow")
        },
        function(){
            $(".t4_a4").hide("slow")
        }
    );
    $(".t5").hover(
        function(){
            $(".t5_a5").show("slow")
        },
        function(){
            $(".t5_a5").hide("slow")
        }
    );
    $(".t7").hover(
        function(){
            $(".t7_a7").show("slow")
        },
        function(){
            $(".t7_a7").hide("slow")
        }
    );
    $(".t9").hover(
        function(){
            $(".t9_a9").show("slow")
        },
        function(){
            $(".t9_a9").hide("slow")
        }
    );
    $(".p2").hover(
        function(){
            $(".p2_a2").show("slow")
        },
        function(){
            $(".p2_a2").hide("slow")
        }
    );
    $(".p4").hover(
        function(){
            $(".p4_a4").show("slow")
        },
        function(){
            $(".p4_a4").hide("slow")
        }
    );
    $(".p7").hover(
        function(){
            $(".p7_a7").show("slow")
        },
        function(){
            $(".p7_a7").hide("slow")
        }
    );
    $(".p9").hover(
        function(){
            $(".p9_a9").show("slow")
        },
        function(){
            $(".p9_a9").hide("slow")
        }
    );
    $(".two_code").hover(
        function(){
            $(".two_code_info").show()
        },
        function(){
            $(".two_code_info").hide("slow")
        }
    );
});